POST http://localhost:3001/api/plans
Content-Type: application/json

{
	"title": "Do fitness exercises",
	"description": "Do some exercises which will improve your fitness with YAOG.",
	"weekday": 1,
	"starting": "10:30",
	"ending": "11:30"
}

